@SOC_SteamPM_BE_HostAddress = http://localhost:5069

### Tohle vrátí prvních 10 nejlepších výsledků.
## Formát odpovědi: {[{name, appId},...]}
GET {{SOC_SteamPM_BE_HostAddress}}/searchGame?search=Hope%22adsdsan
Accept: application/json

### Tohle vrátí JSON objekt s informacemi o hře a cenovou mapu
## Formát odpovědi { name, další info ke hře.., priceMap: [{ baseCurrency: EUR, basePrice, convertedPrice, }]}
GET {{SOC_SteamPM_BE_HostAddress}}/getPriceMap?appId=4864&currency=CZK
Accept: application/json
